# 配置MySQL数据源
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://106.3.97.45:3336/onlinemall_pms
    driver-class-name: com.mysql.cj.jdbc.Driver
  # 配置nacos注册中心
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
# 配置MyBatis Plus
mybatis-plus:
  mapper-location: classpath*:/mapper/**/*.xml
  # 主键自增
  global-config:
    db-config:
      id-type: auto

# 配置服务端口号
server:
  port: 12000